# Setup
title:               Pyrenaicus
tagline:             ''
description:         'Just a personal notebook on the things I'm learning'
url:                 https://pyrenaicus.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              pyrenaicus
  url:               https://twitter.com/pyrenaic
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
